homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Localization
  currency: !secret home_currency
  country: !secret home_country 
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  # Customization file
  customize: !include customize.yaml
  # URLs
  external_url: !secret external_url
  internal_url: !secret internal_url
  # Packages
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction: false
  
# Enables the frontend
frontend:
  extra_module_url:
    - /local/plugins/card-mod.js?v=3.1.1

# Handles redirects from the My Home Assistant service.
my:

# Enables configuration UI
config:

# Enables the mobile companion app
mobile_app:

# Enable python scripts
python_script:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - !secret reverse_proxy_server

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Voice assistant
assist_pipeline:

# Required for text-to-speech
media_source:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - updater
      - media_player

# Purge database regularly
recorder:
  purge_keep_days: 7
  exclude:
    domains:
      - automation
      - updater
      - camera
      - device_tracker
      - group
      - input_text
      - persistent_notification
      - script
      - sensor
    entities:
      - binary_sensor.updater
    entity_globs:
      - binary_sensor.macbook_pro_*
      - binary_sensor.mqtt_*
      - switch.*_sensor
      - switch.ip_webcam
      - sensor.mqtt_*
      - sensor.*dimmer*

  include:
    domains:
      - light
      - binary_sensor
      - switch
      - sensor
      - sun
      - switch
      - vacuum
    entities:
      - sensor.ip_webcam_motion
      - sensor.oneplus_6t_geocoded_location
      - media_player.tv
      - device_tracker.oneplus_a6013
      - binary_sensor.macbook_pro 
      - binary_sensor.macbook_pro_at_desk

# Track the sun
sun:

# Global variables for templates
input_text:
  video_url:
    name: Video URL
    initial: !secret magic_mirror_video

# MQTT Binary sensors
mqtt:
  binary_sensor:
   - name: Bathroom motion sensor 
     state_topic: "home/OMG_lilygo_rtl_433_ESP/RTL_433toMQTT/Nexa-Security/1/29404962"
     value_template: "{{ value_json.state }}"
     payload_on: "ON"
     payload_off: "OFF"
     device_class: motion     
  event:
    - name: Kids Room Remote
      state_topic: "home/OMG_lilygo_rtl_433_ESP_OOK/RTL_433toMQTT/Nexa-Security/3/32595538"
      <<: &nexa_remote_defaults
        event_types: 
          - 'on' 
          - 'off'
        device_class: "button"
        value_template: |
          { 
            "button": "{{ value_json['id'] }}",
            "unit": {{ value_json['unit'] }},
            "event_type": "{{ value_json['state'] | lower }}",
            "group": {{ iif(value_json['group']) | to_json }}
          }
    - name: Christmas remote
      state_topic: "home/OMG_lilygo_rtl_433_ESP/RTL_433toMQTT/Nexa-Security/3/27478810"
      <<: *nexa_remote_defaults
    - name: Bedroom remote 1
      state_topic: "home/OMG_lilygo_rtl_433_ESP/RTL_433toMQTT/Nexa-Security/0/14508010"
      <<: *nexa_remote_defaults
    - name: Bedroom remote 2
      state_topic: "home/OMG_lilygo_rtl_433_ESP/RTL_433toMQTT/Nexa-Security/0/30301174"
      <<: *nexa_remote_defaults

# Template
template:
  - binary_sensor: 
    - name: Bill Device On  
      state: >
        {{ states("sensor.tasmota_bill_energy_power") | float(0) > 1 | float(0) }}
    - name: Bedside charger 1 charging 
      state: >
        {{ states("sensor.bedside_charger_1_power") | float(0) > 0 | float(0) }}
    - name: Bedside charger 2 charging 
      state: >
        {{ states("sensor.bedside_charger_2_power") | float(0) > 0 | float(0) }}
    - name: MacBook Pro
      state: >
          {{ is_state('binary_sensor.macbook_pro_active', 'on')
             or is_state('binary_sensor.macbook_pro_active_work', 'on') 
          }}
    - name: MacBook Pro at desk
      state: >
          {{ not is_state('sensor.macbook_pro_internal_battery_state', 'Not Charging') }}
    - name: Speakers audio available
      state: >
        {{ is_state('sensor.macbook_pro_oscar_active_audio_output', 'Scarlett 6i6 USB')
            and is_state('binary_sensor.macbook_pro_oscar_audio_output_in_use', 'on') 
            or is_state('media_player.chromecast_audio', ['paused', 'buffering', 'playing']) }} 
  - sensor:
      - name: "Flossing"
        icon: 'mdi:alert'
        state: >
          {{ (now().timetuple().tm_yday % 2 == 0) | iif('🦷', '😁') }}

# Switches
switch:
  - platform: wake_on_lan
    name: Computer Power
    mac: !secret computer_mac
    host: !secret computer_ip
    turn_off: 
      action: script.turn_computer_off

  - platform: group
    name: Speakers
    entities:
      - switch.speaker_left
      - switch.speaker_right

  - platform: group
    name: Kitchen advent candlestick
    entities:
      - switch.tasmota_bub

  - platform: group
    name: Living room christmas tree
    entities:
      - switch.tasmota_bob

  - platform: group
    name: Bedroom advent candlestick
    entities:
      - switch.tasmota_bill

  - platform: group
    name: Magic mirror
    entities:
      - switch.galaxy_tab_s2_screen

  - platform: template
    switches:

      tv_sound:
        friendly_name: TV sound
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', 'true') }}"
        turn_on:
          action: script.toggle_tv_mute
        turn_off:
          action: script.toggle_tv_mute

      hallway_camera: 
        friendly_name: Show hallway camera on TV
        value_template: "{{ is_state_attr('media_player.google_tv', 'media_content_id', states('input_text.video_url')) }}"
        turn_on:
          action: script.cast_magic_mirror_camera
          data:
            media_player: media_player.google_tv
        turn_off:
          action: media_player.turn_off
          data:
            entity_id: media_player.google_tv


# Google Assistant - https://www.home-assistant.io/components/google_assistant
google_assistant:
  project_id: !secret ga_project_id
  service_account: !include google_assistant/service_account.json
  report_state: true
  expose_by_default: false
  entity_config: !include_dir_merge_named google_assistant/entity_config/

# Proxy stream
stream: 

# Channge UI config mode
lovelace:
  mode: yaml
  resources:
    - url: /local/plugins/slider-entity-row.js?v=17.2.1
      type: module
    - url: /local/plugins/fold-entity-row.js?v=2.0.14
      type: module
    - url: /local/plugins/button-card.js?v=3.4.2
      type: module
    - url: /local/plugins/homekit-panel-card.js?v=0.6.2
      type: module
    - url: /local/plugins/slider-button-card.js?v=1.10.3
      type: module
    - url: /local/plugins/vacuum-card.js?v=2.2.5
      type: module
    - url: /local/plugins/mini-media-player-bundle.js?v1.15.0
      type: module
    - url: /local/plugins/auto-entities.js?v1.9.1
      type: module


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# History stats
sensor:
  - platform: history_stats
    name: TV on time
    entity_id: media_player.tv
    state: "on"
    type: time
    start: "{{ 0 }}"
    end: "{{ now() }}"

  - platform: rest
    name: Goodnight playlist story indexes
    resource: !secret spotify_sectionize_url
    verify_ssl: false
    scan_interval: 14400


# Cloud
cloud:

# Wake on LAN
wake_on_lan:

# System health
system_health:

# Notify Group
notify: 
  - name: mobile_app
    platform: group
    services: 
      - action: !secret mobile_device_name

# Light groups 
light:
  - platform: relative_brightness_light_group
    name: Bedroom
    entities:
      - light.bedroom_ceiling
      - light.bedroom_bedside_table_1
      - light.bedroom_bedside_table_2
      - light.bedroom_sideboard
  - platform: relative_brightness_light_group
    name: Kitchen
    entities:
      - light.kitchen_ceiling
      - light.cabinet
  - platform: relative_brightness_light_group
    name: Living room
    entities:
      - light.living_room_window_sill
      - light.living_room_ceiling
      - light.cabinet
      - light.living_room_christmas_star
  - platform: relative_brightness_light_group
    name: Office
    entities:
      - light.office_desk
      - light.office_spotlights
      - light.office_top_corner
  - platform: group
    name: Living Room Ceiling
    entities:
      - light.living_room_ceiling_1
      - light.living_room_ceiling_2
      - light.living_room_ceiling_3
  - platform: group
    name: Office lights
    entities:
      - light.office_top_corner
      - light.office_spotlights
      - light.office_desk_lamp
  - platform: template
    lights:
      flic_twist:
        friendly_name: Flic Twist
        turn_on:

        turn_off:

        set_level:
          action: media_player.volume_set
          target:
            entity_id: media_player.spotify_paq
          data:
            volume_level: "{{ (brightness / 255 * 100)|int / 100 }}"        


shell_command: 
  turn_off_computer: ssh {{ ssh_user }} net rpc shutdown -I {{ ip }} -U {{ user }} -t {{ timeout }}

# Spotcast 
#spotcast: 
#  sp_dc: !secret spotify_sp_dc
#  sp_key: !secret spotify_sp_key

## HELPERS

# Button
input_button:

# Counter
counter: 

# Date/time 
input_datetime:

# Select
input_select:

# Schedule
schedule: 

# Timer
timer:

# Input numbers
input_number:
  tv_volume:
    name: TV Volume
    initial: 8
    min: 0
    max: 16
    step: 1

# Input booleans
input_boolean:
  is_christmas_time:
    name: Is Christmas time
    icon: mdi:string-lights

# Includes 
group: !include groups.yaml
automation ui: !include automations.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
intent_script: !include intent_scripts.yaml


# TODO 
# Add more security:
# Abort shutdown