name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install -y libudev-dev
        pip3 install homeassistant
    - name: Move secrets 
      run: |
        mv travis_secrets.yaml secrets.yaml
    - name: Test with hass check
      run: |
        hass -c . --script check_config
