title: !secret home_name
views:

  - badges:
      - sensor.hacs
      - sensor.mqtt_balcony_temperature
      - sensor.electricity_price
      - sun.sun
      - sensor.ip_webcam_video_connections
      - sensor.ip_webcam_motion
      - sensor.ip_webcam_sound
      - sensor.ip_webcam_battery_temperature      

    cards:

      - title: Balcony
        type: entities      
        entities:
          - switch.balcony_lights
          - sensor.mqtt_balcony_temperature
        show_header_toggle: true

      - title: Bathroom
        type: entities      
        entities:
          - light.bathroom_ceiling
          - binary_sensor.mqtt_bathroom_motion
        show_header_toggle: true

      - title: Bedroom
        type: entities      
        entities:
          - light.bedroom_ceiling
          - switch.bedroom_bedside_table_1
          - switch.bedroom_bedside_table_2
          - switch.bedroom_sideboard_light
          - switch.bedroom_advent_candlestick
        show_header_toggle: true

      - title: Hallway
        type: entities      
        entities:
          - switch.hallway_sideboard_light
          - media_player.hallway_speaker
          - binary_sensor.hallway_motion
          - switch.magic_mirror
          - camera.ip_webcam
        show_header_toggle: true

      - title: Kitchen
        type: entities      
        entities:
          - light.kitchen_ceiling
          - switch.advent_candlestick
          - light.cabinet
          - media_player.kitchen_display
          - sensor.mqtt_kitchen_humidity
          - sensor.mqtt_kitchen_temperature
        show_header_toggle: true

      - title: Living Room
        type: entities      
        entities:
          - light.living_room_ceiling
          - light.living_room_window_sill
          - media_player.google_tv
          - media_player.living_room_speaker
          - media_player.tv
          - vacuum.robocop
        show_header_toggle: true

      - title: Office
        type: entities      
        entities:
          - light.office_spotlights
          - light.office_top_corner
          - light.office_desk_lamp
          - media_player.chromecast_audio
          - switch.computer_power
        show_header_toggle: true   

      - title: Kids room
        type: entities      
        entities:
          - light.kids_room_ceiling
          - switch.butterfly
          - switch.star
        show_header_toggle: true   

      - entity: camera.ip_webcam
        type: picture-entity

      - entities:
          - script.send_robocop_to_waste_bin
          - script.turn_tv_on
          - script.cast_magic_mirror_camera
          - script.turn_everything_off

        title: Switch
        type: entities

      - entity: weather.home
        type: weather-forecast

      - entity: weather.smhi_home
        type: weather-forecast

    panel: false
    path: default_view
    title: Home

