name: Check Home Assistant configuration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy dummy secrets for workflow
      run: |
        mv ci/dummy_secrets.yaml secrets.yaml
    - name: Copy dummy service account for workflow
      run: |
        mv ci/dummy_service_account.json google_assistant/service_account.json        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install homeassistant colorlog
    - name: Check Home Assistant config
      run: |
        hass -c . --script check_config
