name: Check Home Assistant configuration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy dummy secrets for workflow
      run: |
        mv travis_secrets.yaml secrets.yaml
    - name: Set up Python 3.12.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install homeassistant
    - name: Check Home Assistant config
      run: |
        hass -c . --script check_config
